handle_query:
  description: >
    Process the user message: {message}
    Current date: {current_date}
    Current time: {current_time}

    Task: Analyze the user's message and delegate to the appropriate specialist.

    Delegation Rules:
    1. For appointment-related queries (schedule, appointment, meeting):
       - Delegate to: "Appointment Management Specialist"
       - Include current date/time for context

    2. For general queries (weather, web search, information):
       - Delegate to: "General Information Assistant"
       - Include any relevant search terms or context

    Available Specialists:
    - Appointment Management Specialist
    - General Information Assistant
  expected_output: "A clear and helpful response to the user's query."
  variables:
    - message
    - current_date
    - current_time
