handle_query:
  description: |
    Process the user message: {message}

    For appointment-related queries (containing words like schedule, appointment, meeting, etc.),
    delegate to the Appointment Management Specialist.

    For all other queries (weather, general information, web searches),
    delegate to the General Information Assistant.

    Note: Use exact role names for delegation:
    - General Information Assistant
    - Appointment Management Specialist
  expected_output: "A clear and helpful response to the user's query."
